### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by kapilbindal** [CheshtaK/Divide#1]
I am running into this issue while running this application. Do you have any ideas what can cause this?

**Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex**

**Comment by CheshtaK** [comment]
Try adding the following lines in your build.gradle : 

implementation 'android.arch.lifecycle:runtime:1.1.1'
implementation 'android.arch.lifecycle:extensions:1.1.1'
implementation 'android.arch.lifecycle:compiler:1.1.1'

This solved the problem for me :')
